name: Pipeline Déploiement Continu & Perf Foot

on:
  push:
    branches: [ "main" ]

jobs:
  perf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      # 1. On démarre ton site de foot directement dans la pipeline
      - name: Démarrer le site de foot
        run: |
          docker build -t site-foot .
          docker run -d --name mon-site-foot -p 8082:80 site-foot
          sleep 3

      # 2. On lance le test K6 (en ciblant localhost puisque tout est dans la même machine)
      - name: Exécution du Test K6
        run: |
          # On modifie temporairement l'adresse pour la pipeline
          sed -i 's/host.docker.internal/localhost/g' script-k6.js
          docker build -f Dockerfile.k6 -t test-foot-k6 .
          docker run --rm --network="host" test-foot-k6

      # 3. On prépare et on lance Gatling
      - name: Créer le dossier résultats Gatling
        run: mkdir -p gatling-results

      - name: Exécuter Gatling
        run: |
          # On adapte le script Gatling pour cibler localhost au lieu de host.docker.internal
          sed -i 's/host.docker.internal/localhost/g' FootSimulation.scala
          docker run --rm \
            --network="host" \
            -v "${{ github.workspace }}:/opt/gatling/user-files/simulations" \
            -v "${{ github.workspace }}/gatling-results:/opt/gatling/results" \
            denvazh/gatling:latest -s football.FootSimulation

      # 4. On stocke le rapport HTML dans les Artifacts !
      - name: Sauvegarder le rapport Gatling (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: rapport-gatling-performance
          path: gatling-results/
          retention-days: 5

      # 5. AJOUT DE L'EXERCICE SÉCURITÉ : Scan OWASP ZAP (+3 points)
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8082'
          rules_file_name: '.zap/rules.tsv' # <--- C'est ici la magie !
          fail_action: true